// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_CLcZ2OnlVOtTaWEU9wmdnRDTCL-UUuU',
    appId: '1:1011178472436:web:e1b756557a07d11c9cefa1',
    messagingSenderId: '1011178472436',
    projectId: 'narapidana-latihan-uts',
    authDomain: 'narapidana-latihan-uts.firebaseapp.com',
    storageBucket: 'narapidana-latihan-uts.firebasestorage.app',
    databaseURL: 'https://narapidana-latihan-uts-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_CLcZ2OnlVOtTaWEU9wmdnRDTCL-UUuU',
    appId: '1:1011178472436:android:e1b756557a07d11c9cefa1',
    messagingSenderId: '1011178472436',
    projectId: 'narapidana-latihan-uts',
    storageBucket: 'narapidana-latihan-uts.firebasestorage.app',
    databaseURL: 'https://narapidana-latihan-uts-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmHPMhZ5CeYvjLtKBxPAw80j3oysLPRzI',
    appId: '1:1011178472436:ios:e58edf27766e6d479cefa1',
    messagingSenderId: '1011178472436',
    projectId: 'narapidana-latihan-uts',
    storageBucket: 'narapidana-latihan-uts.firebasestorage.app',
    iosBundleId: 'com.example.narapidana',
  );
}
